package com.campusfix.service;

import com.campusfix.dto.*;
import com.campusfix.entity.*;
import com.campusfix.exception.*;
import com.campusfix.repository.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.Instant;
import java.util.*;

@Service
public class IssueService {
    private final IssueRepository issues; private final LocationRepository locations; private final UserRepository users; private final AssignmentRepository assignments; private final IssueStatusHistoryRepository history; private final VerificationRecordRepository verifications; private final FeedbackRepository feedback; private final NotificationService notification;
    public IssueService(IssueRepository issues, LocationRepository locations, UserRepository users, AssignmentRepository assignments, IssueStatusHistoryRepository history, VerificationRecordRepository verifications, FeedbackRepository feedback, NotificationService notification) { this.issues = issues; this.locations = locations; this.users = users; this.assignments = assignments; this.history = history; this.verifications = verifications; this.feedback = feedback; this.notification = notification; }
    @Transactional public IssueResponse create(IssueCreateRequest r, User reporter) { Location l = new Location(); l.setBuilding(r.location().building()); l.setBlock(r.location().block()); l.setFloor(r.location().floor()); l.setRoom(r.location().room()); l.setDetails(r.location().details()); Issue i = new Issue(); i.setTitle(r.title()); i.setDescription(r.description()); i.setCategory(r.category()); i.setPriority(r.priority()); i.setLocation(locations.save(l)); i.setReportedBy(reporter); Issue saved = issues.save(i); notification.notify(reporter, saved, NotificationType.ISSUE_SUBMITTED, "Issue submitted"); return IssueResponse.of(saved); }
    public Issue find(Long id) { return issues.findById(id).orElseThrow(() -> new ResourceNotFoundException("Issue not found")); }
    public IssueResponse get(Long id, User actor) { Issue i = find(id); if (actor.getRole() == Role.STUDENT || actor.getRole() == Role.FACULTY) assertOwner(i, actor); return IssueResponse.of(i); }
    public List<IssueResponse> list(User actor) { List<Issue> list = (actor.getRole() == Role.STUDENT || actor.getRole() == Role.FACULTY) ? issues.findByReportedById(actor.getId()) : issues.findAll(); return list.stream().map(IssueResponse::of).toList(); }
    @Transactional public IssueResponse assign(Long id, Long staffId, User admin) { Issue i = find(id); User staff = users.findById(staffId).orElseThrow(() -> new ResourceNotFoundException("Maintenance staff not found")); if (staff.getRole() != Role.MAINTENANCE) throw new BadRequestException("Selected user is not maintenance staff"); assignments.findByIssueIdAndActiveTrue(id).ifPresent(a -> { a.setActive(false); assignments.save(a); }); Assignment a = new Assignment(); a.setIssue(i); a.setMaintenanceStaff(staff); a.setAssignedBy(admin); assignments.save(a); transition(i, IssueStatus.ASSIGNED, admin, "Assigned to maintenance staff"); notification.notify(staff, i, NotificationType.ISSUE_ASSIGNED, "Issue assigned to you"); return IssueResponse.of(i); }
    @Transactional public IssueResponse resolve(Long id, ResolveIssueRequest request, User staff) { Issue i = find(id); Assignment a = assignments.findByIssueIdAndActiveTrue(id).orElseThrow(() -> new BadRequestException("Issue is not assigned")); if (!a.getMaintenanceStaff().getId().equals(staff.getId())) throw new BadRequestException("Issue is not assigned to you"); i.setResolutionRemarks(request.remarks()); i.setResolvedAt(Instant.now()); transition(i, IssueStatus.RESOLVED, staff, request.remarks()); transition(i, IssueStatus.VERIFICATION_PENDING, staff, "Waiting for independent verification"); notification.notify(i.getReportedBy(), i, NotificationType.ISSUE_RESOLVED, "Issue is ready for verification"); return IssueResponse.of(i); }
    @Transactional public IssueResponse verify(Long id, VerificationRequest request, User verifier) { Issue i = find(id); if (i.getStatus() != IssueStatus.VERIFICATION_PENDING) throw new BadRequestException("Issue is not awaiting verification"); VerificationRecord v = new VerificationRecord(); v.setIssue(i); v.setVerifier(verifier); v.setDecision(request.decision()); v.setRemarks(request.remarks()); verifications.save(v); transition(i, request.decision() == VerificationDecision.APPROVED ? IssueStatus.VERIFIED : IssueStatus.REJECTED, verifier, request.remarks()); if (request.decision() == VerificationDecision.APPROVED) { transition(i, IssueStatus.USER_CONFIRMATION_PENDING, verifier, "Awaiting reporter confirmation"); notification.notify(i.getReportedBy(), i, NotificationType.CONFIRMATION_REQUIRED, "Please confirm resolution"); } else { transition(i, IssueStatus.IN_PROGRESS, verifier, "Verification rejected"); notification.notify(i.getReportedBy(), i, NotificationType.VERIFICATION, "Verification rejected; maintenance work resumed"); } return IssueResponse.of(i); }
    @Transactional public IssueResponse confirm(Long id, boolean confirmed, String reason, User reporter) { Issue i = find(id); assertOwner(i, reporter); if (i.getStatus() != IssueStatus.USER_CONFIRMATION_PENDING) throw new BadRequestException("Issue is not awaiting confirmation"); if (confirmed) { i.setClosedAt(Instant.now()); transition(i, IssueStatus.CLOSED, reporter, "Confirmed by reporter"); notification.notify(i.getReportedBy(), i, NotificationType.ISSUE_CLOSED, "Issue closed"); } else { if (reason == null || reason.isBlank()) throw new BadRequestException("A reopen reason is required"); transition(i, IssueStatus.REOPENED, reporter, reason); transition(i, IssueStatus.IN_PROGRESS, reporter, reason); notification.notify(i.getReportedBy(), i, NotificationType.ISSUE_REOPENED, reason); } return IssueResponse.of(i); }
    @Transactional public void feedback(Long id, FeedbackRequest request, User reporter) { Issue i = find(id); assertOwner(i, reporter); if (i.getStatus() != IssueStatus.CLOSED) throw new BadRequestException("Feedback is available after closure"); if (feedback.existsByIssueId(id)) throw new BadRequestException("Feedback already submitted"); Feedback f = new Feedback(); f.setIssue(i); f.setSubmittedBy(reporter); f.setRating(request.rating()); f.setComment(request.comment()); feedback.save(f); }
    @Transactional public IssueResponse status(Long id, IssueStatusUpdateRequest request, User actor) { Issue i = find(id); if (actor.getRole() == Role.STUDENT || actor.getRole() == Role.FACULTY) assertOwner(i, actor); transition(i, request.status(), actor, request.remarks()); return IssueResponse.of(i); }
    private void transition(Issue i, IssueStatus target, User actor, String remarks) { if (!allowed(i.getStatus(), target, actor.getRole())) throw new BadRequestException("Invalid status transition"); IssueStatus previous = i.getStatus(); i.setStatus(target); issues.save(i); IssueStatusHistory h = new IssueStatusHistory(); h.setIssue(i); h.setPreviousStatus(previous); h.setNewStatus(target); h.setChangedBy(actor); h.setRemarks(remarks); history.save(h); notification.notify(i.getReportedBy(), i, NotificationType.STATUS_CHANGED, "Issue status changed to " + target); }
    private boolean allowed(IssueStatus from, IssueStatus to, Role role) { return switch (from) { case REPORTED -> to == IssueStatus.UNDER_REVIEW && role == Role.ADMIN; case UNDER_REVIEW -> to == IssueStatus.ASSIGNED && role == Role.ADMIN; case ASSIGNED -> to == IssueStatus.IN_PROGRESS && role == Role.MAINTENANCE; case IN_PROGRESS -> to == IssueStatus.RESOLVED && role == Role.MAINTENANCE; case RESOLVED -> to == IssueStatus.VERIFICATION_PENDING && role == Role.MAINTENANCE; case VERIFICATION_PENDING -> (to == IssueStatus.VERIFIED || to == IssueStatus.REJECTED) && role == Role.VERIFIER; case VERIFIED -> to == IssueStatus.USER_CONFIRMATION_PENDING && role == Role.VERIFIER; case USER_CONFIRMATION_PENDING -> (to == IssueStatus.CLOSED || to == IssueStatus.REOPENED) && (role == Role.STUDENT || role == Role.FACULTY); case REJECTED, REOPENED -> to == IssueStatus.IN_PROGRESS && (role == Role.MAINTENANCE || role == Role.VERIFIER || role == Role.STUDENT || role == Role.FACULTY); default -> false; }; }
    private void assertOwner(Issue i, User actor) { if (!i.getReportedBy().getId().equals(actor.getId())) throw new BadRequestException("You do not own this issue"); }
}
