package com.campusfix.entity;

public enum IssueStatus {
    REPORTED, UNDER_REVIEW, ASSIGNED, IN_PROGRESS, RESOLVED,
    VERIFICATION_PENDING, VERIFIED, USER_CONFIRMATION_PENDING, CLOSED, REJECTED, REOPENED
}
